//////////////////////////  USERS   /////////////////////////

enum Enum_Rol{
    PENDIENTE ='PENDIENTE',
    ESTUDIANTE = 'ESTUDIANTE',
    ADMINISTRADOR = 'ADMINISTRADOR',
  }


enum Enum_StatusUsers{
    PENDIENTE = 'PENDIENTE',
    AUTORIZADO = 'AUTORIZADO',
    NO_AUTORIZADO = 'NO_AUTORIZADO',
}

enum Enum_AFP {
  COLPENSIONES='COLPENSIONES',
  COLFONDOS='COLFONDOS',
  PORVENIR='PORVENIR',
  PROTECCION='PROTECCION',
  SKANDIA='SKANDIA',
}

enum Enum_ARL {
  COLPATRIA='COLPATRIA',
  COLMENA_SEGUROS='COLMENA_SEGUROS',
  LA_EQUIDAD_SEGUROS='LA_EQUIDAD_SEGUROS',
  LIBERTY_SEGUROS_DE_VIDA_SA='LIBERTY_SEGUROS_DE_VIDA_SA',
  MAPFRE_SEGUROS='MAPFRE_SEGUROS',
  POSITIVA='POSITIVA',
  SEGUROS_BOLIVAR_SA='SEGUROS_BOLIVAR_SA', 
}

enum Enum_EPS {
  MEDIMAS='MEDIMAS',
  FAMISANAR='FAMISANAR',
  NUEVA_EPS='NUEVA_EPS',
  SALUD_TOTAL='SALUD_TOTAL',
  SURA='SURA',
  ALIANSALUD='ALIANSALUD',
  SANITAS='SANITAS',
  COMPENSAR='COMPENSAR',
  COOMEVA='COOMEVA',
  SALUDVIDA='SALUDVIDA',
  CAFESALUD='CAFESALUD',
  COMFANDI='COMFANDI', 
}

enum Enum_RH {
  A_POSITIVO='A +',
  A_NEGATIVO='A -',
  B_POSITIVO='B +',
  B_NEGATIVO='B -',
  AB_POSITIVO='AB +',
  AB_NEGATIVO='AB -',
  O_POSITIVO='O +',
  O_NEGATIVO ='O -',
}
enum Enum_Issuance {
  MADRE='MADRE',
  PADRE='PADRE',
  TIO='TIO',
  HERMANO='HERMANO',
  ABUELA='ABUELA',
  ABUELO='ABUELO',
  OTRO='OTRO',
  
}
enum Enum_Locality {
  ANTONIO_NARINIO='ANTONIO_NARINIO',
  BARRIOS_UNIDOS='BARRIOS_UNIDOS',
  BOSA='BOSA',
  CHAPINERO='CHAPINERO',
  CIUDAD_BOLIVAR='CIUDAD_BOLIVAR',
  ENGATIVA='ENGATIVA',
  FONTIBON='FONTIBON',
  KENNEDY='KENNEDY',
  CANDELARIA='CANDELARIA',
  MARTIRES='MARTIRES',
  PUENTE_ARANDA='PUENTE_ARANDA',
  RAFAEL_URIBE_URIBE='RAFAEL_URIBE_URIBE',
  SAN_CRISTOBAL='SAN_CRISTOBAL',
  SANTA_FE='SANTA_FE',
  SUBA='SUBA',
  SUMAPAZ='SUMAPAZ',
  TEUSAQUILLO='TEUSAQUILLO',
  TUNJUELITO='TUNJUELITO',
  USAQUEN='USAQUEN',
  USME ='USME',
}




export {Enum_Rol, Enum_StatusUsers, Enum_AFP, Enum_ARL, Enum_EPS, Enum_RH, Enum_Issuance, Enum_Locality }